[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[functions."search"]
  external_node_modules = []

[functions."scraper-batdongsan"]
  external_node_modules = []

[functions."alonhadat"]
  external_node_modules = []
